title: Aleksandra Denisova
description: Some space to share my thoughts, projects, and poetry.
theme: jekyll-theme-minimal

# Навигация
nav:
  - title: "Home"
    url: /
  - title: "Poetry"
    url: /poetry
  - title: "Studying & Teaching"
    url: /studying